"""follow table creation

Revision ID: 7788d5546191
Revises: b796f708fd2a
Create Date: 2025-12-26 21:41:03.804256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7788d5546191'
down_revision: Union[str, Sequence[str], None] = 'b796f708fd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('documents_object_key_key'), 'documents', type_='unique')
    op.create_index(op.f('ix_documents_object_key'), 'documents', ['object_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_object_key'), table_name='documents')
    op.create_unique_constraint(op.f('documents_object_key_key'), 'documents', ['object_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
