"""Add performance indexes for API optimization

Revision ID: a5f4a7340681
Revises: c1d2e3f4g5h6
Create Date: 2026-01-16 01:08:06.277416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f4a7340681'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4g5h6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - safely drop indexes if they exist."""
    # These drops were likely auto-generated in error or for a specific environment.
    # On a fresh DB, they might not exist yet, causing crashes.
    # We use 'IF EXISTS' to ensure the migration succeeds.
    op.execute('DROP INDEX IF EXISTS idx_bookmarks_document_id')
    op.execute('DROP INDEX IF EXISTS idx_bookmarks_user_document')
    op.execute('DROP INDEX IF EXISTS idx_comments_document_id')
    op.execute('DROP INDEX IF EXISTS idx_documents_user_visibility')
    op.execute('DROP INDEX IF EXISTS idx_follows_follower_id')
    op.execute('DROP INDEX IF EXISTS idx_follows_following_id')
    op.execute('DROP INDEX IF EXISTS idx_likes_document_id')
    op.execute('DROP INDEX IF EXISTS idx_likes_user_document')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_likes_user_document'), 'likes', ['user_id', 'document_id'], unique=False)
    op.create_index(op.f('idx_likes_document_id'), 'likes', ['document_id'], unique=False)
    op.create_index(op.f('idx_follows_following_id'), 'follows', ['following_id'], unique=False)
    op.create_index(op.f('idx_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_index(op.f('idx_documents_user_visibility'), 'documents', ['user_id', 'visibility', 'is_deleted'], unique=False)
    op.create_index(op.f('idx_comments_document_id'), 'comments', ['document_id'], unique=False)
    op.create_index(op.f('idx_bookmarks_user_document'), 'bookmarks', ['user_id', 'document_id'], unique=False)
    op.create_index(op.f('idx_bookmarks_document_id'), 'bookmarks', ['document_id'], unique=False)
    # ### end Alembic commands ###
