"""Add performance indexes for API optimization

Revision ID: a5f4a7340681
Revises: c1d2e3f4g5h6
Create Date: 2026-01-16 01:08:06.277416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f4a7340681'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4g5h6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_bookmarks_document_id'), table_name='bookmarks')
    op.drop_index(op.f('idx_bookmarks_user_document'), table_name='bookmarks')
    op.drop_index(op.f('idx_comments_document_id'), table_name='comments')
    op.drop_index(op.f('idx_documents_user_visibility'), table_name='documents')
    op.drop_index(op.f('idx_follows_follower_id'), table_name='follows')
    op.drop_index(op.f('idx_follows_following_id'), table_name='follows')
    op.drop_index(op.f('idx_likes_document_id'), table_name='likes')
    op.drop_index(op.f('idx_likes_user_document'), table_name='likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_likes_user_document'), 'likes', ['user_id', 'document_id'], unique=False)
    op.create_index(op.f('idx_likes_document_id'), 'likes', ['document_id'], unique=False)
    op.create_index(op.f('idx_follows_following_id'), 'follows', ['following_id'], unique=False)
    op.create_index(op.f('idx_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_index(op.f('idx_documents_user_visibility'), 'documents', ['user_id', 'visibility', 'is_deleted'], unique=False)
    op.create_index(op.f('idx_comments_document_id'), 'comments', ['document_id'], unique=False)
    op.create_index(op.f('idx_bookmarks_user_document'), 'bookmarks', ['user_id', 'document_id'], unique=False)
    op.create_index(op.f('idx_bookmarks_document_id'), 'bookmarks', ['document_id'], unique=False)
    # ### end Alembic commands ###
